### ISSUE TITLE
"Error: Can't find type DateTime." when using internal values for enum

### ISSUE THREAD

**Issue by AdamTorma** [excitement-engineer/graphql-iso-date#120]
In my resolvers, I use something like:

```javascript
const resolvers = {
  AllowedColor: {
    RED: '#f00',
    GREEN: '#0f0',
    BLUE: '#00f',
  }
};
```
(example taken from the [Apollo Docs](https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values))

Unfortunately, adding these internal values results in an error:

> C:\...\node_modules\graphql-tools\dist\transforms\visitSchema.js:1
Error: Can't find type DateTime.

Everything works fine when using "regular" enums without internal values. On the other hand, the code above works as intended when graphql-iso-date isn't used.

I made [this codesandbox](https://codesandbox.io/s/enum-issue-yq0rl?fontsize=14&hidenavigation=1&theme=dark), just uncomment the section with the enum resolver to see the problem in action.

Any ideas how to fix this issue?

**Comment by AdamTorma** [comment]
It seems like the bug is in Apollo / graphql-tools, not in graphql-iso-date, so this issue can be **closed**!

**Comment by fierysolid** [comment]
It looks like I was able to resolve this by making sure the names match what is defined in the graphql-iso-date Scalar files:

resolvers:
```
DateTime: GraphQLDateTime
Date: GraphQLDate
Time: GraphQLTime
```

schema:
```
scalar DateTime
scalar Date
scalar Time
```

**Comment by aks30498** [comment]
@AdamTorma I'm facing the same issue, how did you fix it ?
