### ISSUE TITLE
How to use with buildSchema?

### ISSUE THREAD

**Issue by ffxsam** [excitement-engineer/graphql-iso-date#37]
How does one use this custom scalar if we're using `buildSchema` to build our schema, e.g.:

```js
module.exports = buildSchema(`
  type User {
    id: ID!
    email: String!
    firstName: String!
    lastName: String!
    signupDate: DateTime!
  }
```

**Comment by excitement-engineer** [comment]
It does not seem to be possible. Check [this](https://github.com/graphql/graphql-js/issues/497) issue in graphql-js for more information. However, you could check out [graphql-tools](http://dev.apollodata.com/tools/graphql-tools/scalars.html) if you want to create an executable schema with custom scalars. Hope this helps!

**Comment by ffxsam** [comment]
Thanks! I already switched to using Apollo's `graphql-server` which works much better with custom scalars.
