### ISSUE TITLE
Troublesome 0000-00-00 00:00:00 DateTime values in database

### ISSUE THREAD

**Issue by J-F-Liu** [excitement-engineer/graphql-iso-date#64]
How to return null instead of throw Error for invalid DateTime?

**Comment by excitement-engineer** [comment]
Hey @J-F-Liu. If the `DateTime` field that you are using is nullable then you could write some custom logic in your code to identify these types of invalid dates and convert them to null before being serialized by GraphQL. This way your API will return null. 

Is this a solution to your problem?

**Comment by J-F-Liu** [comment]
No better place to insert this logic, I'd rather implement DateTime type locally.

**Comment by excitement-engineer** [comment]
Then you can either fork this repo and release your own version on npm or you can simply copy the files in this project into your project and make the adjustment there (there are only a few files and 0 dependencies). Hopefully this solves the issue.
