### ISSUE TITLE
Accept UNIX timestamp in milliseconds as a valid input

### ISSUE THREAD

**Issue by gajus** [excitement-engineer/graphql-iso-date#90]
Seems odd that ES native expression of time (UNIX timestamp in milliseconds) is not supported as a valid input; only the truncated (seconds) format is accepted. This requires a superfluous `new Date(timestamp)` wrapper.

**Comment by gajus** [comment]
> AFAIK timestamps are represented in seconds.

What do you mean by that?

In JavaScript, the standard is milliseconds.

```js
> Date.now()
< 1531860891892

```

**Comment by StefanYohansson** [comment]
what he meant is that **UNIX timestamp** is represented in seconds. (I think the issue title leads to confusion)

> The Unix epoch (or Unix time or POSIX time or Unix timestamp) is the number of seconds that have elapsed since January 1, 1970

**Comment by excitement-engineer** [comment]
@StefanYohansson, yes the definition for UNIX timestamps is in seconds, not milliseconds like in JS.
