### ISSUE TITLE
Support coercing ISO8601 compatible strings in results

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [excitement-engineer/graphql-iso-date#92]
I'm receiving dates in the ISO8601 compatible format 2018-06-13T18:24:53.000+0000 from a database.
GraphQLDateTime from graphql-iso-date won't parse these strings into dates because of the lack of a colon in the timezone offset part.

I'm automatically creating resolvers and objects from a database schema (salesforce describe), and it's a bit hacky to test if i'm receiving a date field from the database and then convert from the 8601 string to a Date object or a 3339 string.

Ideally graphql-iso-date should also support the limited ISO8601 grammar as described in Appendix A of the ISO3339 RFC. This would allow for parsing most dates, without having to handle the full mess that is the ISO8601 format.

I'll probably open a pull request in a few days once I get some free time and see how big an undertaking this will be

**Comment by excitement-engineer** [comment]
Hey @WhiteAbeLincoln, is a timezone without a colon allowed according to RFC 3339?

If this is a blocker then you can always copy the files over to your project and make the necessary changes or you could fork the code. This project is relatively small so this is a good option to go:)

**Comment by WhiteAbeLincoln** [comment]
No, according to RFC 3339 the timezone must have a colon. Section 5.6 lists the ABNF for the timezone as 
```ABNF
time-numoffset  = ("+" / "-") time-hour ":" time-minute
time-offset = "Z" / time-numoffset
```

I have a workaround for now, but I may just fork this project in the future if I want a more general solution.
Thanks!
