### ISSUE TITLE
Support 2018-06-29T03:14:59.085+0000

### ISSUE THREAD

**Issue by linonetwo** [excitement-engineer/graphql-iso-date#93]
It can be recognized by new Date(), but I have to add resolver for DateTime:
```js
  createdAt({ createdAt }) {
    return new Date(createdAt);
  },
```

**Comment by linonetwo** [comment]
And 1527462253000 don't recognize by `graphql-iso-date` either.

**Comment by linonetwo** [comment]
And how about 2018-06-27T10:51:44.000 ?

**Comment by linonetwo** [comment]
I got these date format from EOS blockchain program.

**Comment by excitement-engineer** [comment]
Hey @linonetwo, graphql-iso-date allows for returning `Date` instances, RFC 3339 compliant datetime strings and timestamp. So your timestamp should be recognized. Can you outline what you are running into. Is it returning errors?

**Comment by linonetwo** [comment]
I got this error:

```
"TypeError: DateTime cannot represent an invalid date-time-string 2018-07-16T18:51:40.156+0000.",
            "    at serialize (/Users/linonetwo/Desktop/repo/scaneos_graphql/node_modules/graphql-iso-date/dist/dateTime/index.js:46:13)"
```

**Comment by linonetwo** [comment]
https://github.com/excitement-engineer/graphql-iso-date/blob/master/src/utils/validator.js#L121 actually don't support `2018-07-16T18:51:40.156+0000`, so that validation function returns false.

And `1527462253000` didn't pass `MAX_INT`'s test in https://github.com/excitement-engineer/graphql-iso-date/blob/master/src/utils/validator.js#L150

**Comment by alewiahmed** [comment]
I've got this same issue. Any solution for this?

**Comment by linonetwo** [comment]
@alewiahmed Hi, I actually fork the code here and modify it:

```js
/* eslint-disable eqeqeq */
// @flow
import { GraphQLScalarType, Kind } from 'graphql';
import type { GraphQLScalarTypeConfig } from 'graphql'; // eslint-disable-line

const config: GraphQLScalarTypeConfig<Date, string> = {
  name: 'DateTime',
  description:
    'A date-time string at UTC, such as 2007-12-03T10:15:30Z, ' +
    'compliant with the `date-time` format outlined in section 5.6 of ' +
    'the RFC 3339 profile of the ISO 8601 standard for representation ' +
    'of dates and times using the Gregorian calendar.',
  serialize(value) {
    const date = new Date(value);
    if (date == 'Invalid Date') {
      throw new TypeError(
        `${'DateTime cannot be serialized from a non string, non numeric or non Date type '}${JSON.stringify(
          value,
        )}`,
      );
    }
    return date.toISOString();
  },
  parseValue(value) {
    if (!(typeof value === 'string' || value instanceof String)) {
      throw new TypeError(`DateTime cannot represent non string type ${JSON.stringify(value)}`);
    }

    const date = new Date(value);
    if (date == 'Invalid Date') {
      throw new TypeError(`DateTime cannot represent an invalid date-time-string ${value}.`);
    }
    return date;
  },
  parseLiteral(ast) {
    if (ast.kind !== Kind.STRING) {
      throw new TypeError(`DateTime cannot represent non string type ${String(ast.value != null ? ast.value : null)}`);
    }
    const { value } = ast;
    const date = new Date(value);
    if (date == 'Invalid Date') {
      throw new TypeError(`DateTime cannot represent an invalid date-time-string ${String(value)}.`);
    }
    return date;
  },
};

export default new GraphQLScalarType(config);

```

**Comment by linonetwo** [comment]
It works for me in my last project. But I don't know the opinion of maintainer, so I didn't send a PR.

**Comment by alewiahmed** [comment]
@linonetwo Thanks for your fast response. I appreciate it.

**Comment by excitement-engineer** [comment]
Time offsets +0000 and -0000 are not valid according to the RFC 3339 document (see [here](https://github.com/excitement-engineer/graphql-iso-date/blob/8979ce83785c446e618535d2d4690f419dd5643f/rfc3339.txt#L414)). If you need to support this functionality then the best solution would be to fork the code or else copy the code into the project you are working on. The amount of code for a scalar is relatively limited so hopefully this won't be an issue. Hope this helps:)

**Comment by brunopopf** [comment]
You can do this with straight javascript

`new Date().toISOString()`
