### ISSUE TITLE
graphql@14.0.0 has released

### ISSUE THREAD

**Issue by cncolder** [excitement-engineer/graphql-iso-date#98]
Update peerDependencies in `package.json`.

https://github.com/graphql/graphql-js/releases/tag/v14.0.0

**Comment by excitement-engineer** [comment]
I pushed version 3.6.1 which adds support for it:)

**Comment by zefexdeveloper** [comment]
@excitement-engineer 14.0.2 is released. In the peer dependency it's listed as `^14.0.0`
